// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdKXDDooP_XGk-7KxFfOSCMzP8c4aqWY',
    appId: '1:358757766407:web:7ae30ae18d4748585c21a2',
    messagingSenderId: '358757766407',
    projectId: 'real-time-chat-applicati-85034',
    authDomain: 'real-time-chat-applicati-85034.firebaseapp.com',
    databaseURL:
        'https://real-time-chat-applicati-85034-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-chat-applicati-85034.firebasestorage.app',
    measurementId: 'G-X66GMZSF0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6IemazhgxmUVcCNtTr4rKl6PtyECRq2A',
    appId: '1:358757766407:android:6f6e72df54ce79eb5c21a2',
    messagingSenderId: '358757766407',
    projectId: 'real-time-chat-applicati-85034',
    databaseURL:
        'https://real-time-chat-applicati-85034-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-chat-applicati-85034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtJMYd5I1A6H0fWXUSOGQbYunuhRI7O98',
    appId: '1:358757766407:ios:fe27c5b47fd7fce65c21a2',
    messagingSenderId: '358757766407',
    projectId: 'real-time-chat-applicati-85034',
    databaseURL:
        'https://real-time-chat-applicati-85034-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-chat-applicati-85034.firebasestorage.app',
    iosBundleId: 'com.example.chatKare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtJMYd5I1A6H0fWXUSOGQbYunuhRI7O98',
    appId: '1:358757766407:ios:fe27c5b47fd7fce65c21a2',
    messagingSenderId: '358757766407',
    projectId: 'real-time-chat-applicati-85034',
    databaseURL:
        'https://real-time-chat-applicati-85034-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-chat-applicati-85034.firebasestorage.app',
    iosBundleId: 'com.example.chatKare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdKXDDooP_XGk-7KxFfOSCMzP8c4aqWY',
    appId: '1:358757766407:web:41dbf7cc34ed7eff5c21a2',
    messagingSenderId: '358757766407',
    projectId: 'real-time-chat-applicati-85034',
    authDomain: 'real-time-chat-applicati-85034.firebaseapp.com',
    databaseURL:
        'https://real-time-chat-applicati-85034-default-rtdb.firebaseio.com',
    storageBucket: 'real-time-chat-applicati-85034.firebasestorage.app',
    measurementId: 'G-74XLFCBPED',
  );
}
